export const actionType = {
  FETCH_CHAT: 'FETCH_CHAT',
  ADD_CHAT: 'ADD_CHAT',
  DELETE_CHAT: 'DELETE_CHAT',
  FETCH_BOT_MSG: 'FETCH_BOT_MSG',
  EDIT_CHAT: 'EDIT_CHAT',
  FETCH_CHAT_MSG:"FETCH_CHAT_MSG",
  DELETE_MSG: 'DELETE_MSG',
}
